#
# Module manifest for module 'PSNLog'
#
# Generated by: Maik Koster
#
# Generated on: 3/22/2018
#
# !Custom modification! Add-CMTraceLayoutRenderer modified to accept component parameter and is now executed outside the .psm1 file
@{

    # Script module or binary module file associated with this manifest.
    RootModule             = 'PSNLog.psm1'

    # Version number of this module.
    ModuleVersion          = '0.2.5'

    # Supported PSEditions
    # CompatiblePSEditions = @()

    # ID used to uniquely identify this module
    GUID                   = 'fe52b5c2-b2f8-4804-87c6-8606410b8f7d'

    # Author of this module
    Author                 = 'Maik Koster'

    # Company or vendor of this module
    CompanyName            = 'Unknown'

    # Copyright statement for this module
    Copyright              = '(c) 2018 Maik Koster. All rights reserved.'

    # Description of the functionality provided by this module
    Description            = 'Wrapper for NLog to easily use NLog logging capabilities in PowerShell.'

    # Minimum version of the Windows PowerShell engine required by this module
    PowerShellVersion      = '3.0'

    # Name of the Windows PowerShell host required by this module
    # PowerShellHostName = ''

    # Minimum version of the Windows PowerShell host required by this module
    # PowerShellHostVersion = ''

    # Minimum version of Microsoft .NET Framework required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
    DotNetFrameworkVersion = '4.5'

    # Minimum version of the common language runtime (CLR) required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
    # CLRVersion = ''

    # Processor architecture (None, X86, Amd64) required by this module
    # ProcessorArchitecture = ''

    # Modules that must be imported into the global environment prior to importing this module
    # RequiredModules = @()

    # Assemblies that must be loaded prior to importing this module
    RequiredAssemblies     = 'NLog.dll'

    # Script files (.ps1) that are run in the caller's environment prior to importing this module.
    # ScriptsToProcess = @()

    # Type files (.ps1xml) to be loaded when importing this module
    # TypesToProcess = @()

    # Format files (.ps1xml) to be loaded when importing this module
    # FormatsToProcess = @()

    # Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
    # NestedModules = @()

    # Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
    FunctionsToExport      = 'Disable-NLogLogging', 'Enable-NLogLogging', 'Get-NLogConfiguration', 
    'Get-NLogLogger', 'New-NLogFileTarget', 'New-NLogRule', 
    'New-NLogTarget', 'Read-NLogConfiguration', 'Set-NLogConfiguration', 
    'Test-NLogLogging', 'Write-NLogError', 'Write-NLogHost', 
    'Write-NLogVerbose', 'Write-NLogWarning', 'Add-CMTraceLayoutRenderer'

    # Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
    CmdletsToExport        = @()

    # Variables to export from this module
    VariablesToExport      = @()

    # Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
    AliasesToExport        = @()

    # DSC resources to export from this module
    # DscResourcesToExport = @()

    # List of all modules packaged with this module
    # ModuleList = @()

    # List of all files packaged with this module
    # FileList = @()

    # Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
    PrivateData            = @{
        PSData = @{
            LicenseUri = 'https://github.com/MaikKoster/PSNLog/blob/master/LICENSE'
            Tags       = @(
                'PowerShell', 
                'Logging', 
                'NLog'
            )
            ProjectUri = 'https://github.com/MaikKoster/PSNLog'
        }
    }

    # HelpInfo URI of this module
    HelpInfoURI            = 'http://github.com/MaikKoster/PSNLog/blob/master/PSNLog/en-US/'

    # Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
    # DefaultCommandPrefix = ''

}

